# Generated by Django 5.1.7 on 2025-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(choices=[('feature', 'Feature'), ('improvement', 'Improvement'), ('bug', 'Bug'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('review', 'Code Review'), ('support', 'Customer Support'), ('other', 'Other')], default='feature', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_at', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_users', models.ManyToManyField(blank=True, null=True, related_name='tasks', to='task_manager.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
